// Common
def mainDir="Chapter09/mini-project"
def region="ap-northeast-2"
def deployHost="10.0.22.81"

// Repository Info
def repository="test"
def baseImageTag="base-image"
def appImageTag="app-image"

// Nexus
def nexusUrl="10.0.3.112:5000"
def nexusProxyUrl="10.0.3.112:5001"

// AWS ECR
def ecrLoginHelper="docker-credential-ecr-login"
def ecrUrl="504441673365.dkr.ecr.ap-northeast-2.amazonaws.com"


pipeline {
    agent any

    stages {
        stage('Checkout and Pull Codes from Github Repository'){
            steps{
                checkout scm
            }
        }
        stage('Build Base Image by Docker') {
            steps {
                sh """
                cd ${mainDir}/base-image
                echo 'test' | docker login -u 'test' --password-stdin ${nexusUrl}
                echo 'test' | docker login -u 'test' --password-stdin ${nexusProxyUrl}
                docker build -t ${nexusUrl}/nexus-custom-repository:${baseImageTag} .
                docker push ${nexusUrl}/nexus-custom-repository:${baseImageTag}
                """
            }
        }           
        stage('Scan Static Codes Quality by Jacoco and SonarQube') {
            steps {
                sh """
                cd ${mainDir}
                ./gradlew jacocoTestCoverageVerification --info
                ./gradlew jacocoTestReport --info
                ./gradlew sonarqube --info
                """
            }
        }        
        stage('Clean and Build Codes by Gradle') {
            steps {
                sh """
                cd ${mainDir}
                ./gradlew clean build --info
                """
            }
        }
        stage('Build Docker Image by Jib & Push to Nexus Custom Repository') {
            steps {
                sh """
                    cd ${mainDir}
                    ./gradlew jib -Djib.to.image=${nexusUrl}/nexus-custom-repository:${appImageTag} -DsendCredentialsOverHttp=true -Djib.console='plain'
                """
            }
        }
        stage('Build Docker Image by Jib & Push to AWS ECR Repository') {
            steps {
                withAWS(region:"${region}", credentials:"aws-key") {
                    ecrLogin()
                    sh """
                        curl -O https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.4.0/linux-amd64/${ecrLoginHelper}
                        chmod +x ${ecrLoginHelper}
                        mv ${ecrLoginHelper} /usr/local/bin/
                        cd ${mainDir}
                        ./gradlew jib -Djib.to.image=${ecrUrl}/pwj-test:${appImageTag} -Djib.console='plain'
                    """
                }
            }
        }        
        stage('Scan Security CVE at Clair Scanner') {
            steps {
                script {
                    try {
                        jenkins_ip = sh(script: "docker inspect -f '{{ .NetworkSettings.IPAddress }}' jenkins", returnStdout: true).trim()
                        clair_ip = sh(script: "docker inspect -f '{{ .NetworkSettings.IPAddress }}' clair", returnStdout: true).trim()
                        sh """
                            apt update
                            apt install -y wget
                            docker pull ${nexusUrl}/nexus-custom-repository:${appImageTag}
                            wget https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64
                            chmod +x clair-scanner_linux_amd64
                            mv clair-scanner_linux_amd64 /usr/local/bin/clair-scanner
                        """
                        sh "clair-scanner --ip ${jenkins_ip} --clair='http://${clair_ip}:6060' --log='clair.log' \
                                --report='report.txt' ${nexusUrl}/nexus-custom-repository:${appImageTag}"
                    } catch (err) {
                        echo err.getMessage()
                    }
                }
                echo currentBuild.result
            }
        }
        stage('Deploy Nexus Repository to AWS EC2 VM'){
            steps{
                sshagent(credentials : ["deploy-key"]) {
                    sh "ssh -o StrictHostKeyChecking=no ubuntu@${deployHost} \
                      'echo \"<Nexus repo PW>\" | docker login -u <Nexus repo ID> --password-stdin ${nexusUrl}; \
                      docker run -d -p 81:8080 -t ${nexusUrl}/nexus-custom-repository:${appImageTag};'"
                }
            }
        }
        stage('Deploy AWS ECR Repository to AWS EC2 VM'){
            steps{
                sshagent(credentials : ["deploy-key"]) {
                    sh "ssh -o StrictHostKeyChecking=no ubuntu@${deployHost} \
                     'aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${ecrUrl}/pwj-test; \
                      docker run -d -p 82:8080 -t ${ecrUrl}/pwj-test:${appImageTag};'"
                }
            }
        }
    }
}
